services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/ascertain

  db:
    image: pgvector/pgvector:pg17
    volumes:
      - ascertain_postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ascertain
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 10
      start_period: 10s

volumes:
  ascertain_postgres_data:

networks:
  app_network:
